version: '3'

services:
      
  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    #command: redis-server --save 20 1 --loglevel warning

  goapp:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/app
    expose:
      - "8080"
    extra_hosts:
      - "localhost:127.0.0.1"
    depends_on:
      - redis